### ISSUE TITLE
Add URL bar size

### ISSUE THREAD

**Issue by phucbm** [viivue/frontend-debug#22]
Add one info row for "URL bar", and place this row below the row Document (see the screenshot).

Formula: `URL bar size = document height - viewport height`

![IMG_03CDFEB6CA34-1](https://github.com/viivue/frontend-debug/assets/14942380/9de92fc4-8d18-47bf-bc8e-40fee0a596a6)

**Comment by anj20** [comment]
I would like to work on it can u assign it to me?

**Comment by phucbm** [comment]
> I would like to work on it can u assign it to me?

Thank you, but I'm afraid I can't. We've already got someone to handle this.
